import os
from pathlib import Path
import importlib.util,sys,json,subprocess
from playwright.sync_api import sync_playwright
B=Path(os.environ.get('GMC_LAB_DIR','.scratch/ensemble-atelier')).resolve()
S=Path(__file__).resolve().parents[2]/'game-music-composer/scripts'
O=B/'qa/results';sys.path.insert(0,str(S))
import refine_performance as R
cue={'id':'bridge_fixture','title':'Puente de partitura','category':'mystery','bpm':96,'beats':16,'bars':4,'barLength':4,'meter':'4/4','key':'D','mode':'dorian','voice_budget':8,'events':[], 'instrument_map':{'piano':{'family':'keys'},'flute':{'family':'wind'}}}
for i in range(16):cue['events'].append({'kind':'note','inst':'piano' if i%2 else 'flute','role':'harmony' if i%2 else 'lead','midi':60+[2,4,5,9][i%4],'beat':float(i),'duration':.7,'gain':.05,'velocity':80,'velocity_gain':1})
source=O/'native-format-fixture.json';dest=O/'native-refined-fixture.json';html=O/'native-bridge.html'
source.write_text(json.dumps(cue,indent=2));dest.unlink(missing_ok=True);html.unlink(missing_ok=True)
subprocess.run([sys.executable,str(S/'refine_performance.py'),str(source),str(dest),'--profile','pocket','--amount','0.65'],check=True)
subprocess.run([sys.executable,str(S/'visualize_score.py'),'--input',str(dest),'--output',str(html)],check=True)
refined=json.loads(dest.read_text());checks=[];errors=[]
def ck(name,v):checks.append({'name':name,'pass':bool(v)});assert v,name
ck('written event structure preserved across real Python CLI',R.structural_hash(cue)==R.structural_hash(refined))
ck('actual performance timing changed',any(e['performance_beat']!=e['beat'] for e in refined['events']))
with sync_playwright() as p:
 browser=p.chromium.launch(executable_path=os.environ.get('CHROMIUM_EXECUTABLE','/usr/bin/chromium'),headless=True,args=['--no-sandbox'])
 page=browser.new_page(viewport={'width':1440,'height':1050});page.on('pageerror',lambda e:errors.append(str(e)))
 page.set_content(html.read_text());page.wait_for_function('window.LAB?.score?.origin === "imported-symbolic-score"')
 ck('native-format 16 events visible in two instruments',page.evaluate('LAB.score.events.length===16 && LAB.score.tracks.length===2'))
 pairs=page.evaluate('LAB.score.events.map(e=>[e.midi,e.performedBeat])')
 ck('performed onsets reach viewer exactly',pairs==[[e['midi'],e['performance_beat']] for e in refined['events']])
 original=page.evaluate('LAB.signature()');page.locator('#play').click();page.wait_for_function('LAB.transport.playing',timeout=60000);page.wait_for_timeout(350)
 ck('native-format viewer prepares and plays',page.evaluate('LAB.transport.playing && LAB.sound.ctx.state==="running"'))
 page.locator('#stop').click();page.locator('#reset').click()
 ck('reset preserves embedded cue rather than a demo',page.evaluate('LAB.signature()')==original)
 ck('explicit synthetic loss report',page.evaluate('LAB.score.importReport.losses.length>0'))
 ck('no JS errors',not errors);browser.close()
report={'scope':'Real added Python helpers + browser. Fixture in native shape, NOT generated by neospc.py and NOT native audio renderer.', 'checks':checks,'errors':errors}
(O/'native-bridge-report.json').write_text(json.dumps(report,indent=2)+'\n');print('PASS',len(checks))
