#!/usr/bin/env python3
"""Validate Neo-SPC distribution boundaries before a release."""
from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
from pathlib import Path

import package_skill


SKILL_ROOT = Path(__file__).resolve().parents[1]
REPO_ROOT = SKILL_ROOT.parent
ARCHIVE_ROOT = REPO_ROOT / "game-music-composer-maintainer"
ARCHIVE_MANIFEST = ARCHIVE_ROOT / "archive-manifest.json"
TEXT_SUFFIXES = {".json", ".md", ".py", ".sha256", ".txt", ".yaml", ".yml"}
FORBIDDEN_PATH = b"/mnt" + b"/data"


def path_lint_issues() -> list[str]:
    issues: list[str] = []
    for path in package_skill.source_files():
        relative = path.relative_to(SKILL_ROOT).as_posix()
        if path.suffix.lower() in TEXT_SUFFIXES and FORBIDDEN_PATH in path.read_bytes():
            issues.append(f"non-portable Linux mount path in runtime: {relative}")
        if "__pycache__" in path.parts or path.suffix.lower() in {".pyc", ".pyo"}:
            issues.append(f"generated bytecode in runtime source list: {relative}")
    return issues


def archive_issues() -> list[str]:
    issues: list[str] = []
    if not (REPO_ROOT / ".git").exists():
        return issues
    if not ARCHIVE_MANIFEST.is_file():
        return [f"missing archive manifest: {ARCHIVE_MANIFEST}"]
    try:
        manifest = json.loads(ARCHIVE_MANIFEST.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        return [f"invalid archive manifest JSON: {exc}"]
    if manifest.get("source_root") != "game-music-composer":
        issues.append("archive manifest source_root must be game-music-composer")
    if manifest.get("archive_root") != "historical/skill-package":
        issues.append("archive manifest archive_root must be historical/skill-package")
    entries = manifest.get("preserved_paths")
    if not isinstance(entries, list) or not entries:
        return issues + ["archive manifest must declare preserved_paths"]
    seen: set[str] = set()
    archive_base = (ARCHIVE_ROOT / "historical" / "skill-package").resolve()
    for entry in entries:
        if not isinstance(entry, dict):
            issues.append(f"invalid archive manifest entry: {entry!r}")
            continue
        source = entry.get("source")
        archive = entry.get("archive")
        if (
            not isinstance(source, str)
            or not source
            or Path(source).is_absolute()
            or ".." in Path(source).parts
            or not isinstance(archive, str)
            or not archive
            or Path(archive).is_absolute()
            or ".." in Path(archive).parts
        ):
            issues.append(f"invalid archive manifest entry: {entry!r}")
            continue
        if source in seen:
            issues.append(f"duplicate archive source entry: {source}")
            continue
        seen.add(source)
        archive_path = (archive_base / archive).resolve()
        if not archive_path.is_relative_to(archive_base):
            issues.append(f"archive entry escapes archive root: {archive}")
            continue
        if not archive_path.is_file():
            issues.append(f"missing preserved historical file: {archive}")
        if (SKILL_ROOT / source).exists():
            issues.append(f"historical file still ships in runtime: {source}")
    return issues


def manifest_issues() -> list[str]:
    issues: list[str] = []
    if not package_skill.MANIFEST.is_file():
        return ["missing runtime MANIFEST.sha256"]
    expected = {
        f"./{path.relative_to(SKILL_ROOT).as_posix()}": hashlib.sha256(path.read_bytes()).hexdigest()
        for path in package_skill.source_files()
        if path != package_skill.MANIFEST
    }
    actual: dict[str, str] = {}
    for line in package_skill.MANIFEST.read_text(encoding="utf-8").splitlines():
        try:
            digest, relative = line.split("  ", 1)
        except ValueError:
            issues.append(f"malformed manifest line: {line!r}")
            continue
        actual[relative] = digest
    if actual != expected:
        issues.append("MANIFEST.sha256 does not match the distributable runtime files")
    return issues


def tree_issues() -> list[str]:
    issues: list[str] = []
    bytecode = subprocess.run(
        ["git", "ls-files"], cwd=REPO_ROOT, text=True, capture_output=True, check=False
    )
    if bytecode.returncode:
        return [f"could not inspect git index: {bytecode.stderr.strip()}"]
    tracked_generated = [
        path for path in bytecode.stdout.splitlines() if path.endswith((".pyc", ".pyo")) or "/__pycache__/" in path
    ]
    if tracked_generated:
        issues.append("tracked generated bytecode: " + ", ".join(tracked_generated))
    status = subprocess.run(
        ["git", "status", "--porcelain", "--untracked-files=all"], cwd=REPO_ROOT, text=True, capture_output=True, check=False
    )
    if status.returncode:
        issues.append(f"could not inspect git status: {status.stderr.strip()}")
    elif status.stdout.strip():
        dirty = ", ".join(status.stdout.splitlines())
        issues.append(f"working tree is not clean after release checks: {dirty}")
    return issues


def release_issues(check_tree: bool = False) -> list[str]:
    issues = path_lint_issues() + archive_issues() + manifest_issues()
    if check_tree:
        issues.extend(tree_issues())
    return issues


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check-tree", action="store_true", help="Also require a clean index and working tree.")
    args = parser.parse_args()
    issues = release_issues(check_tree=args.check_tree)
    if issues:
        print("FAIL Neo-SPC release gate")
        for issue in issues:
            print(f"- {issue}")
        return 1
    print("PASS Neo-SPC release gate")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
