/* Five independent Brainstormer experiences share only the verified event/audio/view contract. */
(function(){'use strict';
const M=MusicLab,A=SynthLab,V=VisualLab,C=LAB_CONFIG,$=id=>document.getElementById(id),E=V.esc;
const DEFAULTS={instrumentarium:{ensemble:'chamber',capture:false,cursor:0},pocket:{style:'neo',mode:'pocket',amount:.65,swing:.12,lead:16,bass:-4},conversation:{mode:'dialogue',space:.5,answer:.6,seed:7},atlas:{genre:'neo',melodyGenre:'same',density:.52,seed:17},cycles:{periods:[8,12,16],hits:[3,5,5],rotations:[0,1,3],spacing:.5,method:'interlock',seed:7}};
let params=M.copy(DEFAULTS[C.mode]),score=null,selectedTrack=null,selectedEvent=null,live=[],imported=null,importIndex=0,undo=[],rendering=false,lastDraw=0,raf=null;
const initialInvariant=$('invariant').textContent;
const sound=new A.SoundEngine(),transport=new A.Transport(sound);sound.setVolume(.55);sound.onPrepare=(n,total)=>message(`Preparando voces · ${n}/${total}. Esta partitura quedará en caché.`);
Atelier.createScope(document.querySelector('.toolbar'));
const stage=new V.Stage($('instruments'),playNote,selectTrack,toggleMute,toggleSolo);
const roll=new V.PianoRoll($('roll'),selectEvent);
function message(text,error=false){$('status').textContent=text;$('status').style.color=error?'var(--danger)':'var(--accent2)';}
function elOptions(obj){return Object.entries(obj).map(([id,label])=>`<option value="${E(id)}">${E(typeof label==='object'?label.label:label)}</option>`).join('');}
function choose(id,label,options,value){return `<div class="control"><label for="${id}">${label}</label><select id="${id}">${elOptions(options)}</select></div>`;}
function slider(id,label,value,min=0,max=1,step=.01){return `<div class="control"><label for="${id}">${label}<output id="${id}-value">${value}</output></label><input id="${id}" type="range" min="${min}" max="${max}" step="${step}" value="${value}"></div>`;}
function segments(id,items,value){return `<div class="segmented" id="${id}">${Object.entries(items).map(([k,[name,desc]])=>`<button data-value="${k}" aria-pressed="${value===k}">${name}<small>${desc}</small></button>`).join('')}</div>`;}
function bindSelect(id,field){$(id).value=params[field];$(id).onchange=()=>{params[field]=$(id).value;rebuild();};}
function bindSlider(id,field,format=v=>Math.round(v*100)+'%'){const update=()=>{$(id+'-value').textContent=format(Number($(id).value));};update();$(id).oninput=update;$(id).onchange=()=>{params[field]=Number($(id).value);rebuild();};}
function bindSegments(id,field){$(id).querySelectorAll('button').forEach(b=>b.onclick=()=>{params[field]=b.dataset.value;$(id).querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));rebuild();if(C.mode==='conversation')syncConversationControls();});}
function syncConversationControls(){if(C.mode!=='conversation')return;const noVariation=['tiled','breath'].includes(params.mode);$('variation').disabled=noVariation;$('answer').disabled=noVariation;$('space').disabled=params.mode==='tiled';$('variation').title=noVariation?'Esta sintaxis no contiene un desarrollo variable. Elegí Conversación o Asimétrica.':'Variar sólo el desarrollo';}
function controls(){const host=$('controls');let html='';
 if(C.mode==='instrumentarium'){
 html=choose('ensemble','Ensamble de partida',{chamber:'Cámara / madera y aire',jazz:'Combo / teclas y metal',ritual:'Ritual / cuerda y resonancia'},params.ensemble)+`<div class="control"><label for="patch">56 aliases de la skill + 3 extras</label><select id="patch">${elOptions(M.INST)}</select><div class="capture"><button id="add-instrument" class="small">Añadir instrumento</button><button id="remove-instrument" class="small danger">Quitar seleccionado</button></div></div><div class="control"><label for="preview-engine">Motor de preview</label><select id="preview-engine"><option value="compact">Compacto (paletas actuales)</option><option value="soundfont">SoundFont local (opt-in)</option></select><input type="file" id="sf2-file" accept=".sf2,.sf3,audio/x-soundfont"><p class="hint" id="sf2-status">Por defecto: síntesis compacta. Un SF2 local no sustituye Chamber, Circuit ni los masters grabados del catálogo. Sin CDN.</p></div><div class="control"><label for="file-import">Escuchar un score de la skill</label><input type="file" id="file-import" accept=".json,application/json"><p class="hint">composition.json, catalog.json o sesión del laboratorio. Lectura local; no se envía ningún archivo.</p><select id="catalog-cue" hidden aria-label="Cue del catálogo"></select></div><div class="control"><button id="capture" aria-pressed="false">Grabar pasos · OFF</button><p class="hint" id="capture-info">Tocá las superficies. Cada clic puede añadir una corchea al score.</p><div class="capture"><button class="small" id="capture-start">Cursor al inicio</button><button class="small" id="undo">Deshacer edición</button></div></div>`;
 }else if(C.mode==='pocket'){
 html=segments('interpretations',{grid:['Recta','Posiciones y duraciones originales'],pocket:['Pocket','Ubicación por rol y arco de frase'],jitter:['Azar','Desvíos independientes; no se recomienda por defecto']},params.mode)+choose('groove-source','Material de prueba',{neo:'Combo sincopado',jazz:'Célula con subdivisión ternaria',garage:'Célula 2-step'},params.style)+slider('amount','Intensidad interpretativa',params.amount)+slider('swing','Swing de semicorchea',params.swing,0,.55,.01)+slider('lead-delay','Lead: colocación',params.lead,-30,45,1)+slider('bass-delay','Bajo: colocación',params.bass,-30,30,1);
 }else if(C.mode==='conversation'){
 html=segments('syntax',{tiled:['Copiada','Todos repiten y rellenan'],dialogue:['Conversación','Una voz contesta en el hueco'],asymmetric:['Asimétrica','Frases de 3 + 2 + 3 compases'],breath:['Respiración','Una región realmente se vacía']},params.mode)+slider('space','Espacio del acompañamiento',params.space)+slider('answer','Extensión de respuesta',params.answer)+`<div class="control"><button id="variation">Otra respuesta en desarrollo</button><p class="hint">Semilla <b id="seed-value">${params.seed}</b>. La llamada y el retorno se conservan al variar la semilla; cambiar sintaxis sí los reescribe.</p></div>`;
 }else if(C.mode==='atlas'){
 html=choose('genre','Gramática del acompañamiento',M.GENRES,params.genre)+choose('melody-genre','Sintaxis del gesto melódico',{same:'La misma familia',...M.GENRES},params.melodyGenre)+slider('density','Actividad y huecos',params.density)+`<div class="control"><button id="variation">Variar el desarrollo</button></div><div class="theme-info"><b>Un cruce, no un disfraz.</b><p>La base conserva su gramática rítmica. El motivo adopta otra sintaxis; cambiar el timbre no es la única transformación.</p></div><p class="hint">Cruces originales en afinación temperada. No equivalen a interpretación tradicional ni reemplazan investigación con músicos.</p>`;
 }else{
 html=segments('cycle-method',{interlock:['Entrelazado','Cada ciclo mantiene su duración'],hocket:['Hoquetus','Un ataque por turno entre tres voces'],additive:['Adición','Los ataques entran gradualmente']},params.method)+choose('spacing','Duración de cada paso',{'0.25':'Semicorchea · ¼ beat','0.5':'Corchea · ½ beat','1':'Negra · 1 beat'},params.spacing)+`<p class="hint">Editá longitudes, ataques y rotaciones debajo de cada rueda. Cierre común por MCM, no truncado a 8 compases.</p><div class="control"><button id="variation">Cambiar recorrido melódico</button></div><div class="theme-info"><b>No más = más humano.</b><p>Este proceso puede ser perfectamente cuantizado y aun así tener diálogo. No hace falta desordenar el reloj.</p></div>`;
 }
 host.innerHTML=html;
 if(C.mode==='instrumentarium'){
 $('ensemble').value=params.ensemble;$('ensemble').onchange=()=>{params.ensemble=$('ensemble').value;imported=null;rebuild();};$('patch').value='harp';$('add-instrument').onclick=addInstrument;$('remove-instrument').onclick=removeInstrument;$('capture').onclick=()=>{params.capture=!params.capture;stop();syncCapture();};$('capture-start').onclick=()=>{params.cursor=0;syncCapture();};$('undo').onclick=undoEdit;$('file-import').onchange=loadFile;$('catalog-cue').onchange=()=>{importIndex=Number($('catalog-cue').value);try{setScore(M.importScore(imported,importIndex));message('Cue cargado. Se conserva la partitura; el timbre es una interpretación sintética.');}catch(e){message(e.message,true);}};bindSoundfontControls();
 }else if(C.mode==='pocket'){
 bindSegments('interpretations','mode');bindSelect('groove-source','style');bindSlider('amount','amount');bindSlider('swing','swing');bindSlider('lead-delay','lead',v=>`${v>0?'+':''}${v} ms`);bindSlider('bass-delay','bass',v=>`${v>0?'+':''}${v} ms`);
 }else if(C.mode==='conversation'){
 bindSegments('syntax','mode');bindSlider('space','space');bindSlider('answer','answer');$('variation').onclick=()=>{params.seed++;$('seed-value').textContent=params.seed;rebuild();};syncConversationControls();
 }else if(C.mode==='atlas'){
 bindSelect('genre','genre');bindSelect('melody-genre','melodyGenre');bindSlider('density','density');$('variation').onclick=()=>{params.seed++;rebuild();};
 }else{bindSegments('cycle-method','method');$('spacing').value=String(params.spacing);$('spacing').onchange=()=>{params.spacing=Number($('spacing').value);rebuild();};$('variation').onclick=()=>{params.seed++;rebuild();};}
}
function buildScore(){switch(C.mode){case 'instrumentarium':return M.applyPerformance(M.studioScore(params.ensemble),'pocket',.45,.06,39);case 'pocket':return M.applyPerformance(M.pocketScore(params.style),params.mode,params.amount,params.swing,19,{lead:params.lead,bass:params.bass});case 'conversation':return M.phraseScore(params);case 'atlas':return M.genreScore(params);case 'cycles':return M.cycleScore(params);}}
function rebuild(){try{const s=buildScore();imported=null;setScore(s);special();message('Nueva escucha lista. Los cambios reinician el transporte, sin mezclar versiones.');}catch(e){message(e.message,true);}}
function setScore(s){stop();score=s;transport.setScore(score);selectedTrack=score.tracks.some(t=>t.id===selectedTrack)?selectedTrack:score.tracks[0]?.id;selectedEvent=null;live=[];stage.build(score,selectedTrack);syncState();const f=$('track-filter');const old=f.value;f.innerHTML='<option value="all">Todas las pistas</option>'+score.tracks.map(t=>`<option value="${E(t.id)}">${E(t.label)}</option>`).join('');f.value=score.tracks.some(t=>t.id===old)?old:'all';roll.set(score,f.value,C.mode==='pocket');$('score-title').textContent=score.title;$('roll-legend').innerHTML=score.tracks.map(t=>`<span class="swatch" style="--voice:${M.resolve(t.patch).color}">${E(t.label)}</span>`).join('');$('sections').innerHTML=score.sections.map(s=>`<div class="section-chip" style="flex:${s.end-s.start}">${E(s.name)}</div>`).join('');$('tempo').value=score.bpm;$('tempo-value').textContent=score.bpm;$('editor').classList.remove('show');stats();syncCapture();special();}
function stats(){const m=M.metrics(score);$('stats').innerHTML=`<div class="metric"><span>Eventos / pistas</span><b>${m.notes} / ${m.tracks}</b></div><div class="metric"><span>Duración</span><b>${m.seconds.toFixed(1)} s</b></div><div class="metric"><span>Compases · métrica</span><b>${Number(score.bars.toFixed(2))} · ${score.meter}</b></div><div class="metric"><span>Desviación temporal σ</span><b>${m.timingStd.toFixed(1)} ms</b></div>`;
 if(C.mode==='pocket'){$('invariant').textContent=M.scoreSignature(score)===M.scoreSignature(M.pocketScore(params.style))?'Mismas notas, mismo score. Cambia sólo la interpretación.':'La partitura fue editada manualmente.';}
 if(C.mode==='instrumentarium'&&!score.importReport)$('invariant').textContent=initialInvariant;
 if(C.mode==='instrumentarium'&&score.importReport){$('invariant').textContent=`Importados ${score.events.length} eventos, ${score.tracks.length} pistas. ${score.importReport.fallbacks.length} fallback(s). Sin samples, CC ni buses nativos.`;}
}
function special(){const host=$('special');if(!score)return;
 if(C.mode==='pocket'){host.innerHTML='<section class="panel special-panel"><h2>Colocación respecto de la grilla</h2><canvas class="deviation" id="deviation" aria-label="Desviaciones por rol en milisegundos"></canvas><div class="micro">Cada punto es un ataque. La línea vertical central es el tiempo escrito; negativo = antes, positivo = después.</div></section>';drawDeviation();}
 else if(C.mode==='conversation'){const source=M.phraseScore({...params,seed:7}),preserved=M.scoreSignature({...score,events:score.events.filter(e=>e.protected)})===M.scoreSignature({...source,events:source.events.filter(e=>e.protected)});host.innerHTML=`<section class="panel special-panel"><div class="grammar-grid"><div class="grammar-item"><b>PRIMER PLANO</b>${params.mode==='tiled'?'Flauta continua':'Flauta ↔ clarinete'}</div><div class="grammar-item"><b>SINTAXIS</b>${params.mode==='asymmetric'?'3 + 2 + 3 compases':params.mode==='breath'?'Aparición / aire / regreso':'4 regiones de 2 compases'}</div><div class="grammar-item"><b>ACOMPAÑAR</b>${params.mode==='tiled'?'Arpa ocupa cada corchea':'Retirar el relleno, acortar acordes'}</div><div class="grammar-item"><b>SEMILLA</b>${preserved?'Núcleo inicial y retorno conservados':'El núcleo fue editado'}</div></div></section>`;}
 else if(C.mode==='atlas'){const g=M.GENRES[params.genre],mg=M.GENRES[params.melodyGenre]||g;host.innerHTML=`<section class="panel special-panel"><div class="grammar-grid">${[['RITMO',g.rhythm],['ARMONÍA',g.harmony],['FRASE',mg.phrasing],['SILENCIO',g.silence]].map(([l,t])=>`<div class="grammar-item"><b>${l}</b>${E(t)}</div>`).join('')}</div><div class="note-ribbon">${E(g.knowledge)}</div><div class="source-links">${[...new Set([...g.sources,...mg.sources])].map(id=>{let s=C.sources[id];return s?`<a href="${E(s.url)}" target="_blank" rel="noopener noreferrer">${id} · ${E(s.short)}</a>`:'';}).join('')}</div></section>`;}
 else if(C.mode==='cycles'){
 host.innerHTML=`<section class="panel special-panel"><div class="panel-title"><h2>El encuentro de los ciclos</h2><span class="caption">${score.cycles.commonSteps} pasos · ${score.beats} beats</span></div><div class="cycle-wheels">${score.tracks.map((t,i)=>`<div class="wheel"><header>${E(t.label)}</header><svg id="wheel-${i}" viewBox="0 0 190 180" aria-label="Ciclo ${i+1}, ${params.periods[i]} pasos"></svg><div class="cycle-inputs"><label>Largo<input id="period-${i}" type="number" min="1" max="32" value="${params.periods[i]}"></label><label>Ataques<input id="hits-${i}" type="number" min="0" max="${params.periods[i]}" value="${params.hits[i]}"></label><label>Rotación<input id="rotation-${i}" type="number" min="0" max="31" value="${params.rotations[i]}"></label></div></div>`).join('')}</div><p class="hint">Los círculos muestran la máscara base. Hoquetus y Adición filtran ataques: el piano roll y las teclas muestran el resultado efectivo.</p></section>`;
 for(let i=0;i<3;i++){for(const [name,field]of [['period','periods'],['hits','hits'],['rotation','rotations']]){$(`${name}-${i}`).onchange=()=>{const next=M.copy(params);next[field][i]=Number($(`${name}-${i}`).value);try{M.cycleScore(next);params=next;rebuild();}catch(e){$(`${name}-${i}`).value=params[field][i];message(e.message,true);}};}}
 drawWheels(0);
 }else{host.innerHTML='<section class="panel special-panel"><div class="grammar-grid"><div class="grammar-item"><b>TOCAR</b>Clic en tecla, cuerda o golpe.</div><div class="grammar-item"><b>VER</b>La altura real se ilumina en instrumento y roll.</div><div class="grammar-item"><b>ESCRIBIR</b>Grabar pasos para añadir notas.</div><div class="grammar-item"><b>INSPECCIONAR</b>Clic en una nota del piano roll.</div></div></section>';}
}
function drawDeviation(){const c=$('deviation');if(!c)return;const dpr=Math.min(devicePixelRatio||1,2),w=c.clientWidth||700,h=145;c.width=w*dpr;c.height=h*dpr;const x=c.getContext('2d');x.scale(dpr,dpr);const roles=[...new Set(score.events.map(e=>e.role))],left=90,right=w-16;const max=Math.max(35,...score.events.map(e=>Math.abs((e.performedBeat-e.beat)*60000/score.bpm)))*1.1,center=(left+right)/2,unit=(right-left)/(2*max);x.font='9px ui-monospace';for(const ms of [-max/2,0,max/2]){let px=center+ms*unit;x.strokeStyle=ms===0?'#b5b9a8':'#3b474c';x.beginPath();x.moveTo(px,20);x.lineTo(px,130);x.stroke();x.fillStyle='#9eacae';x.fillText(`${Math.round(ms)} ms`,px-13,12);}roles.forEach((r,i)=>{const y=32+i*100/Math.max(1,roles.length-1);x.fillStyle='#a6b1b1';x.fillText(r,2,y+3);for(const e of score.events.filter(e=>e.role===r)){const ms=(e.performedBeat-e.beat)*60000/score.bpm;x.fillStyle=M.resolve(e.patch).color;x.globalAlpha=.62;x.beginPath();x.arc(center+ms*unit,y+(M.hash(e.id)%7-3),2.1,0,Math.PI*2);x.fill();}x.globalAlpha=1;});}
function drawWheels(position){if(C.mode!=='cycles'||!score.cycles)return;for(let j=0;j<3;j++){const svg=$(`wheel-${j}`);if(!svg)continue;let n=params.periods[j],mask=M.euclid(n,params.hits[j],params.rotations[j]),phase=M.mod(position/params.spacing,n);const color=M.resolve(score.tracks[j].patch).color;if(!svg.childElementCount){svg.append(V.svgEl('circle',{cx:95,cy:87,r:65,fill:'none',stroke:'#3b4b51','stroke-width':1}));svg.append(V.svgEl('text',{x:95,y:86,'text-anchor':'middle',fill:color,'font-size':25,'font-family':'ui-monospace'},`${params.hits[j]}:${n}`));svg.append(V.svgEl('text',{x:95,y:103,'text-anchor':'middle',fill:'#87999e','font-size':9},'ATAQUES / PASOS'));for(let i=0;i<n;i++){let a=i/n*Math.PI*2-Math.PI/2;svg.append(V.svgEl('circle',{cx:95+65*Math.cos(a),cy:87+65*Math.sin(a),r:4.5,'data-step':i,fill:mask[i]?color:'#283238',stroke:'#506168'}));}svg.append(V.svgEl('line',{x1:95,y1:87,x2:95,y2:22,stroke:'#e7e6cc','stroke-width':1.5,'data-cursor':''}));}let a=phase/n*Math.PI*2-Math.PI/2,l=svg.querySelector('[data-cursor]');l.setAttribute('x2',95+58*Math.cos(a));l.setAttribute('y2',87+58*Math.sin(a));for(const node of svg.querySelectorAll('[data-step]'))node.setAttribute('r',Number(node.dataset.step)===Math.floor(phase)&&transport.playing?'6.5':'4.5');}}
function syncState(){stage.state(transport.muted,transport.solo,selectedTrack);}
function selectTrack(id){selectedTrack=id;syncState();if(C.mode==='instrumentarium'){$('patch').value=score.tracks.find(t=>t.id===id)?.patch||'piano';syncCapture();}}
function toggleMute(id){stop();transport.muted.has(id)?transport.muted.delete(id):transport.muted.add(id);syncState();message('Mute aplicado. Volvé a escuchar desde el inicio.');}
function toggleSolo(id){stop();transport.solo=transport.solo===id?null:id;syncState();message('Solo aplicado. Volvé a escuchar desde el inicio.');}
async function playNote(id,midi){try{selectTrack(id);const t=score.tracks.find(t=>t.id===id);if(!t)return;const duration=.52;const event={track:id,patch:t.patch,midi,velocity:.72};const p=await sound.preview(t.patch,midi,duration,.72,t);live.push({...event,until:p.end});if(params.capture&&C.mode==='instrumentarium'){if(params.cursor>=score.beats){message('El cursor llegó al final. Reinicialo para grabar otra frase.',true);return;}saveUndo();M.add(score,id,params.cursor,.45,midi,.72,{decision:'capturado desde instrumento virtual'});params.cursor+=.5;M.finish(score);transport.setScore(score);stage.build(score,selectedTrack);syncState();roll.set(score,$('track-filter').value);stats();syncCapture();}else message(`${t.label} · ${M.noteName(midi)} · MIDI ${midi}`);}catch(e){message(e.message,true);}}
function syncCapture(){if(C.mode!=='instrumentarium'||!$('capture'))return;$('capture').textContent=`Grabar pasos · ${params.capture?'ON':'OFF'}`;$('capture').setAttribute('aria-pressed',String(params.capture));$('capture-info').textContent=`Cursor: beat ${params.cursor.toFixed(1)} / ${score?.beats||32}. ${params.capture?'Cada clic añade una nota de ½ beat; escuchar detiene la captura.':'Tocá libremente o activá la grabación por pasos.'}`;}
function saveUndo(){undo.push(M.copy(score));if(undo.length>15)undo.shift();}
function undoEdit(){if(!undo.length){message('No hay ediciones para deshacer.');return;}setScore(undo.pop());message('Edición deshecha.');}
function addInstrument(){if(score.tracks.length>=12){message('Hasta 12 miniinstrumentos en esta sesión interactiva. Los imports admiten más.',true);return;}saveUndo();const patch=$('patch').value,p=M.resolve(patch),id=`live_${patch}_${Date.now().toString(36)}`;score.tracks.push(M.track(id,patch,p.drum?'drums':'lead',0,.65));selectedTrack=id;setScore(score);message('Instrumento añadido. Tocá su superficie o grabá pasos: no se agregó música de relleno.');}
function removeInstrument(){if(!selectedTrack||score.tracks.length<=1){message('Conservá al menos una pista.',true);return;}saveUndo();score.events=score.events.filter(e=>e.track!==selectedTrack);score.tracks=score.tracks.filter(t=>t.id!==selectedTrack);setScore(score);message('Instrumento y sus eventos quitados; disponible en Deshacer.');}
function bindSoundfontControls(){
 const engineSel=$('preview-engine'),file=$('sf2-file');
 if(!engineSel)return;
 const preview=window.SoundfontLab?new window.SoundfontLab.SoundfontPreview():null;
 if(preview)preview.attach(sound);
 engineSel.value=sound.previewBackend;
 engineSel.onchange=()=>{
  const next=engineSel.value;
  if(next==='soundfont'&&!(preview&&preview.ready)){
   engineSel.value='compact';
   sound.previewBackend='compact';
   message('Cargá un SF2 local primero. Sin SpessaSynth junto al HTML el motor compacto no se apaga.',true);
   return;
  }
  sound.previewBackend=next;
  stop();
  message(next==='soundfont'?'Preview SoundFont en vivo. Chamber, Circuit y los masters grabados no cambian.':'Preview compacto. Paletas actuales intactas.');
 };
 if(file)file.onchange=async()=>{
  try{
   if(!preview)throw Error('Motor SoundFont ausente en este HTML.');
   await sound.init();
   await preview.loadFile(file.files[0]);
   sound.previewBackend='soundfont';
   engineSel.value='soundfont';
   message('SF2 local listo para preview. No es un master del catálogo.');
  }catch(e){message(e.message,true);engineSel.value='compact';sound.previewBackend='compact';}
 };
}
async function loadFile(){const f=$('file-import').files[0];if(!f)return;try{if(f.size>25*1024*1024)throw Error('Máximo 25 MB por archivo.');const parsed=JSON.parse(await f.text());const s=M.importScore(parsed,0);imported=parsed;importIndex=0;saveUndo();setScore(s);if(Array.isArray(parsed.styles)){const sel=$('catalog-cue');sel.hidden=false;sel.innerHTML=parsed.styles.map((x,i)=>`<option value="${i}">${E(String(x?.title||x?.id||`Cue ${i+1}`).slice(0,100))}</option>`).join('');}else $('catalog-cue').hidden=true;message('JSON leído localmente. Notas importadas; audio interpretado con síntesis de boceto. Un SF2 opt-in no sustituye masters grabados.');}catch(e){message('No se importó: '+e.message,true);}}
function selectEvent(e){selectedEvent=e;selectedTrack=e.track;syncState();roll.selectedId=e.id;$('editor').classList.add('show');$('event-name').textContent=`${M.noteName(e.midi)} · ${score.tracks.find(t=>t.id===e.track)?.label}`;$('note-midi').value=e.midi;$('note-beat').value=e.beat;$('note-duration').value=e.duration;$('note-velocity').value=Math.round(e.velocity*127);$('event-meta').textContent=`Escrita ${e.beat.toFixed(3)} · interpretada ${e.performedBeat.toFixed(3)} beats · ${e.articulation}`;}
function applyEdit(){if(!selectedEvent)return;const n=Number($('note-midi').value),b=Number($('note-beat').value),d=Number($('note-duration').value),vel=Number($('note-velocity').value);if(!Number.isInteger(n)||n<0||n>127||!Number.isFinite(b)||b<0||b>=score.beats||!Number.isFinite(d)||d<=0||b+d>score.beats||!Number.isFinite(vel)||vel<1||vel>127){message('Revisá nota, beat, duración y velocity. La nota debe quedar dentro del loop.',true);return;}if(d*60/score.bpm>14){message('Esta síntesis de boceto admite notas de hasta 14 segundos. Reducí la duración.',true);return;}saveUndo();stop();Object.assign(selectedEvent,{midi:n,beat:b,duration:d,velocity:vel/127,performedBeat:b,performedDuration:d,performedVelocity:vel/127,decision:'edición explícita en piano roll'});M.finish(score);const id=selectedEvent.id;setScore(score);selectEvent(score.events.find(e=>e.id===id));message('Nota editada. Audio e instrumento usan los mismos valores.');}
async function play(){try{message('Preparando las voces de esta partitura…');if(params.capture){params.capture=false;syncCapture();}const pending=transport.play();syncTransport();await pending;syncTransport();if(!transport.playing)return;message('Reproduciendo. Clic en una superficie para tocar encima.');}catch(e){message('No se pudo iniciar el audio: '+e.message,true);syncTransport();}}
function stop(){transport.stop();live=[];syncTransport();}
function syncTransport(){$('play').disabled=transport.playing||transport.starting;$('stop').disabled=!transport.playing&&!transport.starting;$('tempo').disabled=transport.playing||transport.starting||rendering;}
transport.onStop=msg=>{message(msg,true);syncTransport();};
function reset(){stop();transport.muted.clear();transport.solo=null;params=M.copy(DEFAULTS[C.mode]);undo=[];imported=null;importIndex=0;selectedTrack=null;sound.setVolume(.55);$('volume').value=55;controls();if(window.__GMC_INITIAL__){setScore(M.importScore(window.__GMC_INITIAL__,0));message('Restablecido el score importado original.');}else{rebuild();message('Restablecido el ejemplo original.');}}
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),2000);}
function session(){return{kind:'gmc-brainstorm-session',version:3,idea:C.id,date:'2026-09-08',params:M.copy(params),score:M.copy(score),audition:{muted:[...transport.muted],solo:transport.solo,volume:sound.volume},scope:'Vista y resíntesis de boceto. Importación Neo-SPC explícita; no paridad con su renderer ni emulación acústica.',human_review:'pending',production_ready:false,visual_preferences:{motion:stage.motion,labels:stage.labels}};}
function exportJSON(){download(new Blob([JSON.stringify(session(),null,2)],{type:'application/json'}),`${C.id}-${C.mode}-sesion.json`);message('Sesión JSON creada. Incluye score y parámetros, no samples ni un proyecto de DAW.');}
async function exportWAV(){if(rendering)return;rendering=true;stop();$('wav').disabled=true;message(sound.previewBackend==='soundfont'?'Sintetizando el WAV con el motor compacto. El SF2 es solo preview en vivo y no sustituye un master.':'Sintetizando el WAV de esta escucha…');try{const previous=sound.previewBackend;sound.previewBackend='compact';await new Promise(r=>setTimeout(r,40));const b=await sound.render(score,{muted:transport.muted,solo:transport.solo});sound.previewBackend=previous;download(A.wav(b),`${C.id}-${C.mode}-boceto.wav`);message('WAV PCM16 estéreo creado: una vuelta + 0,7 s de cola. No es un loop masterizado ni un render FluidSynth.');}catch(e){message('No se exportó: '+e.message,true);}finally{rendering=false;$('wav').disabled=false;syncTransport();}}
function animate(now){if(now-lastDraw>38){lastDraw=now;const audioTime=sound.displayTime();live=live.filter(e=>e.until>audioTime);const active=transport.active(audioTime).concat(live),position=transport.position(audioTime);stage.update(active,audioTime);window.Atelier?.scope?.(sound);roll.draw(position,active);$('time').textContent=`${String(Math.floor(position/score.barLength)+1).padStart(2,'0')} : ${String(Math.floor(M.mod(position,score.barLength))+1).padStart(2,'0')}`;$('sections').querySelectorAll('.section-chip').forEach((x,i)=>x.classList.toggle('active',transport.playing&&position>=score.sections[i].start&&position<score.sections[i].end));drawWheels(position);if(!transport.playing&&!transport.starting&&$('play').disabled&&!rendering)syncTransport();}raf=requestAnimationFrame(animate);}
$('play').onclick=play;$('stop').onclick=()=>{stop();message('Detenido.');};$('reset').onclick=reset;$('json').onclick=exportJSON;$('wav').onclick=exportWAV;$('volume').oninput=()=>sound.setVolume(Number($('volume').value)/100);$('tempo').oninput=()=>{$('tempo-value').textContent=$('tempo').value;};$('tempo').onchange=()=>{stop();const proposed=Number($('tempo').value);if(score.events.some(e=>e.performedDuration*60/proposed>14)){$('tempo').value=score.bpm;$('tempo-value').textContent=score.bpm;message('Ese tempo excede 14 s por nota en este sintetizador de boceto.',true);return;}score.bpm=proposed;stats();special();message('Tempo cambiado; escuchá desde el inicio.');};$('track-filter').onchange=()=>roll.set(score,$('track-filter').value,C.mode==='pocket');$('apply-note').onclick=applyEdit;$('delete-note').onclick=()=>{if(!selectedEvent)return;saveUndo();score.events=score.events.filter(e=>e.id!==selectedEvent.id);setScore(score);message('Nota eliminada.');};$('close-editor').onclick=()=>{$('editor').classList.remove('show');roll.selectedId=null;};$('note-audition').onclick=()=>{if(selectedEvent)playNote(selectedEvent.track,selectedEvent.midi);};
window.addEventListener('resize',()=>{if(C.mode==='pocket')drawDeviation();});
document.addEventListener('visibilitychange',()=>{if(document.hidden){stop();message('Audio detenido al ocultar la pestaña.');}});
window.addEventListener('pagehide',()=>{stop();cancelAnimationFrame(raf);sound.ctx?.close();});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){stop();return;}if(e.target.closest('input,select,textarea,button,[role="button"]')||e.repeat)return;if(e.code==='Space'){e.preventDefault();transport.playing?stop():play();return;}const i='awsedftgyhujk'.indexOf(e.key.toLowerCase());if(i>=0&&selectedTrack){const t=score.tracks.find(t=>t.id===selectedTrack),p=M.resolve(t.patch),n=p.drum?p.midi:Math.max(p.range[0],Math.min(p.range[1]-12,60))+i;playNote(selectedTrack,n);}});
controls();setScore(window.__GMC_INITIAL__?M.importScore(window.__GMC_INITIAL__,0):buildScore());message('Listo. Audio sólo al tocar o pulsar Escuchar. Empezá con volumen bajo.');raf=requestAnimationFrame(animate);
window.LAB={get score(){return score;},get params(){return params;},get selectedTrack(){return selectedTrack;},get live(){return live;},transport,sound,stage,roll,reset,rebuild,play,stop,session,playNote,exportWAV,exportJSON,signature:()=>M.scoreSignature(score)};
})();
