/* Shared track controls and piano roll; instrument bodies live in atelier.js. */
(function(root){'use strict';const M=root.MusicLab;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const black=n=>[1,3,6,8,10].includes(M.mod(n,12));
function svgEl(type,attrs={},text=''){const e=document.createElementNS('http://www.w3.org/2000/svg',type);for(const[k,v]of Object.entries(attrs))e.setAttribute(k,v);if(text)e.textContent=text;return e;}
class Stage{
 constructor(container,onNote,onSelect,onMute,onSolo){this.el=container;this.onNote=onNote;this.onSelect=onSelect;this.onMute=onMute;this.onSolo=onSolo;this.cards=new Map();this.selected=null;this.reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;}
 build(score,selected){this.score=score;this.selected=selected;this.el.replaceChildren();this.cards.clear();for(const t of score.tracks){const p=M.resolve(t.patch),ev=score.events.filter(e=>e.track===t.id);const card=document.createElement('article');card.className='instrument';card.dataset.track=t.id;card.style.setProperty('--voice',p.color);card.innerHTML=`<header><button class="instrument-name" title="Seleccionar instrumento">${esc(t.label||p.label)}</button><span class="role">${esc(t.role)}</span><div class="lane-buttons"><button class="mute" title="Silenciar" aria-label="Silenciar ${esc(t.label||p.label)}" aria-pressed="false">M</button><button class="solo" title="Escuchar solo" aria-label="Solo ${esc(t.label||p.label)}" aria-pressed="false">S</button></div></header><div class="readout"><strong>—</strong><span>${esc(p.surface)} / ${ev.length} notas</span></div><svg class="surface" viewBox="0 0 520 248"></svg><footer><span>${p.drum?'GOLPE':`${M.noteName(p.range[0])}—${M.noteName(p.range[1])}`}</span><div class="level"><i></i></div><span>SYNTH</span></footer>`;
 card.querySelector('.instrument-name').onclick=()=>this.onSelect(t.id);card.querySelector('.mute').onclick=()=>this.onMute(t.id);card.querySelector('.solo').onclick=()=>this.onSolo(t.id);
 for(const key of card.querySelectorAll('[data-note]')){const trigger=()=>this.onNote(t.id,Number(key.dataset.note));key.addEventListener('pointerdown',e=>{e.preventDefault();trigger();});key.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();trigger();}});}
 this.el.appendChild(card);this.cards.set(t.id,card);}this.state(new Set(),null,selected);}
 state(muted,solo,selected){for(const[id,c]of this.cards){c.classList.toggle('selected',id===selected);c.classList.toggle('muted',muted.has(id)||(solo&&solo!==id));c.querySelector('.mute').setAttribute('aria-pressed',String(muted.has(id)));c.querySelector('.solo').setAttribute('aria-pressed',String(solo===id));}}
 update(){}
}

class PianoRoll{
 constructor(canvas,onSelect){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.onSelect=onSelect;this.hit=[];this.filter='all';this.selectedId=null;this.ghosts=false;this.cache=null;canvas.addEventListener('pointerdown',e=>{const r=canvas.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;const hit=this.hit.filter(h=>x>=h.x&&x<=h.x+h.w&&y>=h.y-2&&y<=h.y+h.h+2).reverse()[0];if(hit)this.onSelect(hit.e);});new ResizeObserver(()=>{this.cache=null;this.draw(0,[]);}).observe(canvas);}
 set(score,filter='all',ghosts=false){this.score=score;this.filter=filter;this.ghosts=ghosts;this.cache=null;this.draw(0,[]);}
 base(){const c=this.canvas,w=c.clientWidth||800,h=c.clientHeight||252,dpr=Math.min(window.devicePixelRatio||1,2);c.width=w*dpr;c.height=h*dpr;this.ctx.setTransform(dpr,0,0,dpr,0,0);const x=this.ctx;this.width=w;this.height=h;this.hit=[];x.fillStyle='#161c1f';x.fillRect(0,0,w,h);if(!this.score)return;
 const s=this.score,events=s.events.filter(e=>this.filter==='all'||e.track===this.filter);let low=events.length?Math.floor(Math.min(...events.map(e=>e.midi))/12)*12:36,high=events.length?Math.ceil(Math.max(...events.map(e=>e.midi))/12)*12:84;if(high-low<12)high=low+12;low=M.clamp(low,0,116);high=M.clamp(high,low+12,127);const left=39,top=25,height=h-40,scale=height/(high-low+1),unit=(w-left-10)/s.beats;this.geometry={low,high,left,top,scale,unit};
 for(let n=low;n<=high;n++){const yy=top+(high-n)*scale;x.fillStyle=black(n)?'#192126':'#1e282c';x.fillRect(left,yy,w-left-10,Math.max(.5,scale-.3));if(n%12===0||scale>10){x.fillStyle='#849294';x.font='9px ui-monospace';x.fillText(M.noteName(n),4,yy+Math.max(scale-1,8));}}
 const subdivision=s.beats>64?s.barLength:1;for(let b=0;b<=s.beats;b+=subdivision){const xx=left+b*unit;const bar=Math.abs(M.mod(b,s.barLength))<.01;x.strokeStyle=bar?'#415159':'#28353a';x.lineWidth=bar?1:.5;x.beginPath();x.moveTo(xx,top);x.lineTo(xx,h-13);x.stroke();if(bar&&unit*s.barLength>29){x.fillStyle='#a6b2b2';x.font='10px ui-monospace';x.fillText(String(Math.round(b/s.barLength)+1),xx+4,16);}}
 for(const e of events){const performed=e.performedBeat??e.beat,dur=e.performedDuration??e.duration,xx=left+performed*unit,yy=top+(high-e.midi)*scale,ww=Math.max(3,dur*unit-1),hh=Math.max(3,scale-1);if(this.ghosts){x.strokeStyle='#93a1a454';x.strokeRect(left+e.beat*unit,yy,Math.max(3,e.duration*unit),hh);x.beginPath();x.moveTo(left+e.beat*unit,yy+hh*.5);x.lineTo(xx,yy+hh*.5);x.stroke();}x.globalAlpha=.45+.5*(e.performedVelocity??e.velocity);x.fillStyle=M.resolve(e.patch).color;x.fillRect(xx,yy,ww,hh);this.hit.push({e,x:xx,y:yy,w:ww,h:hh});}x.globalAlpha=1;this.cache=document.createElement('canvas');this.cache.width=c.width;this.cache.height=c.height;this.cache.getContext('2d').drawImage(c,0,0);}
 draw(position=0,active=[]){if(!this.cache)this.base();const x=this.ctx,c=this.canvas;if(this.cache){x.save();x.setTransform(1,0,0,1,0,0);x.drawImage(this.cache,0,0);x.restore();}if(!this.score||!this.geometry)return;const ids=new Set(active.map(e=>e.id));for(const h of this.hit){if(ids.has(h.e.id)||h.e.id===this.selectedId){x.strokeStyle='#edf1de';x.lineWidth=1.4;x.strokeRect(h.x-.5,h.y-.5,h.w+1,h.h+1);}}
 const xx=this.geometry.left+position*this.geometry.unit;x.strokeStyle='#dfbb88';x.lineWidth=1.4;x.beginPath();x.moveTo(xx,22);x.lineTo(xx,this.height-9);x.stroke();x.fillStyle='#dfbb88';x.beginPath();x.moveTo(xx-4,21);x.lineTo(xx+4,21);x.lineTo(xx,27);x.fill();}
}
root.VisualLab={Stage,PianoRoll,esc,svgEl};
})(globalThis);
