#!/usr/bin/env python3
"""Build and verify Studio v2 banks in a fresh directory, then publish explicitly."""
import argparse
import base64
import copy
import hashlib
import json
from pathlib import Path
import shutil
import subprocess
import sys
import zipfile
import numpy as np
import soundfile as sf

ROOT = Path(__file__).resolve().parents[1]
SKILL = ROOT/'game-music-composer'
STUDIO = ROOT/'game-music-composer-showcase'
sys.path.insert(0, str(SKILL/'scripts'))
from synthesize_soundbanks import VERSION, ORIGINAL_PATCHES, synthesize


def read(path): return json.loads(path.read_text(encoding='utf-8'))
def write(path, value):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, indent=2, ensure_ascii=False, allow_nan=False)+'\n', encoding='utf-8', newline='\n')
def sha(path): return hashlib.sha256(path.read_bytes()).hexdigest()
def embedded(path): return 'data:audio/wav;base64,'+base64.b64encode(path.read_bytes()).decode()
def js(path, variable, value):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text('window.'+variable+'='+json.dumps(value, separators=(',',':'))+';\n', encoding='utf-8', newline='\n')


def build(output):
    output.mkdir(parents=True, exist_ok=False)
    receipt = {'version':VERSION, 'generator_sha256':sha(SKILL/'scripts/synthesize_soundbanks.py'),
               'catalog_sha256':sha(SKILL/'data/neospc100-benchmark-v4.1.json'), 'samples':[], 'files':{}}
    with zipfile.ZipFile(output/'previous-banks.zip','w',zipfile.ZIP_STORED) as z:
        for folder in [SKILL/'resources/original-sample-bank', STUDIO/'assets/bank-preview', STUDIO/'data/banks']:
            for p in folder.rglob('*'):
                if p.is_file(): z.write(p,p.relative_to(ROOT))
        for p in [SKILL/'data/instrument-calibration.json',SKILL/'data/factory-bank-manifest.json',STUDIO/'data/factory-bank.js',STUDIO/'data/sample-bank.js',STUDIO/'data/factory-bank-previews.js']:
            z.write(p,p.relative_to(ROOT))

    def save(path, patch, midi, vel, rr, sr, looped):
        x, loop = synthesize(patch,midi,vel,rr,sr,looped)
        if not np.isfinite(x).all() or not .02 < np.max(np.abs(x)) <= .9:
            raise ValueError(f'Invalid signal: {path}')
        path.parent.mkdir(parents=True,exist_ok=True)
        sf.write(path,x,sr,subtype='PCM_24' if sr==44100 else 'PCM_16')
        y, rate = sf.read(path,dtype='float32')
        rms = float(np.sqrt(np.mean(y*y)))
        seam = None
        if loop:
            start,end=[round(loop[k]*sr) for k in ['start_sec','end_sec']]
            seam = float(abs(y[start]-y[end-1]))
            natural = float(abs(y[start]-y[start-1]))
            if abs(seam-natural)>2/32768: raise ValueError(f'Loop discontinuity: {path}')
        receipt['samples'].append({'file':path.relative_to(output).as_posix(),'sha256':sha(path),'sample_rate':rate,'frames':len(y),'peak':float(np.max(np.abs(y))),'rms':rms,'dc':float(np.mean(y)),'loop_step':seam})
        return y,loop

    manifest=read(SKILL/'resources/original-sample-bank/sample-bank.json')
    calibration=read(SKILL/'data/instrument-calibration.json')
    compact={'version':VERSION,'name':'Studio Compact','sample_rate':32000,'samples':{}}
    for s in manifest['samples']:
        sid=s['id'];path=output/'original-sample-bank'/Path(s['file']).name
        y,loop=save(path,ORIGINAL_PATCHES[sid],s['root_midi'],100,1,32000,bool(s.get('loop')))
        if loop:s['loop']=loop
        s.update(bytes_pcm=path.stat().st_size,synthesis_version=VERSION)
        entry=calibration['samples'][sid]
        peak=float(np.max(np.abs(y)))
        active=y[np.abs(y)>peak*.04]
        metric=float(np.sqrt(np.mean(active**2))) if s['category']!='percussion' else peak
        db=20*np.log10(max(metric,1e-9));target=entry['target_value_db']
        gain=min(10**((target-db)/20),.90/max(peak,1e-9))
        spectrum=np.abs(np.fft.rfft(y));freq=np.fft.rfftfreq(len(y),1/32000)
        entry.update(trim_db=round(20*np.log10(gain),4),linear_gain=round(float(gain),7),source_value_db=round(float(db),4),centroid_hz=round(float(np.sum(freq*spectrum)/max(np.sum(spectrum),1e-9)),1),crest_db=round(float(20*np.log10(peak/max(np.sqrt(np.mean(y*y)),1e-9))),2))
        compact['samples'][path.name]={'id':sid,'root_midi':s['root_midi'],'loop':loop,'category':s['category'],'linear_gain':entry['linear_gain'],'data':embedded(path)}
    manifest.update(version=VERSION,provenance='Original CC0 samples generated by scripts/synthesize_soundbanks.py.',rendering_note='Studio Compact v2: body modes, register-aware partials, varied excitation and baked sustain crossfades.')
    calibration.update(version=VERSION,method='Measured active RMS or percussion peak, capped to retain 0.9 source headroom; rebuilt for Studio v2 samples.')
    write(output/'original-sample-bank/sample-bank.json',manifest)
    write(output/'instrument-calibration.json',calibration)
    js(output/'data/sample-bank.js','NEOSPC_SAMPLE_BANK',compact)

    factory=read(SKILL/'data/factory-bank-manifest.json')
    factory.update(name='Studio Multisample',version=VERSION,origin='Original CC0 synthesis from scripts/synthesize_soundbanks.py. No third-party recordings.')
    factory['profiles']['neo16']['neo16_processing']=False
    factory['profiles']['neo32']['preview_only']=True
    data={**factory,'embedded_profile':'neo16','patches':{},'samples':{},'sample_sources':{}}
    previews={}
    for p in factory['patches']:
        roots=p.get('roots') or [p.get('note',60)]
        regions=[];chunk={}
        chunk_name=f"data/banks/{p['id'].replace('.','_')}.js"
        for index,root in enumerate(roots):
            low=p.get('range',[root,root])[0] if index==0 else (roots[index-1]+root)//2+1
            high=p.get('range',[root,root])[1] if index==len(roots)-1 else (root+roots[index+1])//2
            for vel,lo,hi in [(54,1,79),(108,80,127)]:
                for rr in [1,2]:
                    name=f"samples/{p['id'].replace('.','_')}/m{root}_v{vel}_rr{rr}.wav"
                    path=output/name
                    _,loop=save(path,p['id'],root,vel,rr,32000,bool(p.get('loop')))
                    regions.append({'file':name,'root':root,'lokey':low,'hikey':high,'lovel':lo,'hivel':hi,'rr':rr,'rr_count':2,'loop':loop})
                    chunk[name]=embedded(path)
                    data['sample_sources'][name]=chunk_name
        preview_root=roots[len(roots)//2]
        name=f"assets/bank-preview/neo32/{p['id'].replace('.','_')}.wav"
        _,loop=save(output/name,p['id'],preview_root,108,1,44100,bool(p.get('loop')))
        p['profiles']={'neo16':{'regions':regions},'neo32':{'regions':[{'file':name,'root':preview_root,'lokey':preview_root,'hikey':preview_root,'lovel':108,'hivel':108,'rr':1,'rr_count':1,'loop':loop}], 'preview_only':True}}
        p['rr']=2
        previews[p['id']]={'file':name,'root':preview_root,'velocity':108}
        data['patches'][p['id']]=copy.deepcopy(p)
        chunk_path=output/chunk_name;chunk_path.parent.mkdir(parents=True,exist_ok=True)
        chunk_path.write_text('Object.assign(window.NEOSPC_FACTORY_BANK.samples,'+json.dumps(chunk,separators=(',',':'))+');\n',encoding='utf-8',newline='\n')
        print(p['id'],len(regions),'regions',flush=True)
    data['stats']={'patches':len(data['patches']),'embedded_samples':len(data['sample_sources'])}
    js(output/'data/factory-bank.js','NEOSPC_FACTORY_BANK',data)
    js(output/'data/factory-bank-previews.js','NEOSPC_FACTORY_PREVIEWS',previews)
    write(output/'factory-bank-manifest.json',factory)
    receipt['stats']={**data['stats'],'compact_samples':len(compact['samples']),'previews':len(previews)}
    for p in output.rglob('*'):
        if p.is_file() and p.name!='previous-banks.zip': receipt['files'][p.relative_to(output).as_posix()]=sha(p)
    write(output/'verification.json',receipt)
    print(receipt['stats'],flush=True)


def publish(output):
    receipt=read(output/'verification.json')
    if receipt.get('palette_generator_sha256') and sha(SKILL/'scripts/studio_timbres.py')!=receipt['palette_generator_sha256']: raise ValueError('Palette generator changed after build')
    if sha(SKILL/'scripts/synthesize_soundbanks.py')!=receipt['generator_sha256']: raise ValueError('Generator changed after build')
    if sha(SKILL/'data/neospc100-benchmark-v4.1.json')!=receipt['catalog_sha256']: raise ValueError('Catalog changed after build')
    for name,digest in receipt['files'].items():
        if sha(output/name)!=digest: raise ValueError(f'Changed verified output: {name}')
    for p in (output/'original-sample-bank').iterdir(): shutil.copyfile(p,SKILL/'resources/original-sample-bank'/p.name)
    for name in ['instrument-calibration.json','factory-bank-manifest.json']:shutil.copyfile(output/name,SKILL/'data'/name)
    if (output/'soundbank-provenance.json').exists():shutil.copyfile(output/'soundbank-provenance.json',SKILL/'data/soundbank-provenance.json')
    for p in (output/'data').rglob('*.js'):
        dest=STUDIO/p.relative_to(output);dest.parent.mkdir(parents=True,exist_ok=True);shutil.copyfile(p,dest)
    for p in (output/'assets').rglob('*.wav'):shutil.copyfile(p,STUDIO/p.relative_to(output))
    print('Published verified Studio v2 banks and 50 previews.')


def publish_audio(output):
    inputs=read(output/'render-inputs.json')
    for name,digest in inputs.items():
        if sha(ROOT/name)!=digest: raise ValueError(f'Render input changed: {name}')
    catalog=read(SKILL/'data/neospc100-benchmark-v4.1.json')
    mix=read(output/'audio/mix-report.json')
    if len(mix)!=100 or any(row.get('skipped') for row in mix): raise ValueError('Need 100 fresh renders')
    records=[]
    for cue in catalog['styles']:
        for ext in ['ogg','mp3']:
            name=cue['id']+'.'+ext;source=output/'audio'/name;dest=STUDIO/'assets/audio'/name
            y,sr=sf.read(source,dtype='float32',always_2d=True)
            expected=cue['beats']*60/cue['bpm']
            if sr!=32000 or y.shape[1]!=2 or abs(len(y)/sr-expected)>.12: raise ValueError(f'Wrong format/duration: {name}')
            if not np.isfinite(y).all() or not 0<float(np.max(np.abs(y)))<1 or np.sqrt(np.mean(y*y))<1e-5: raise ValueError(f'Invalid audio: {name}')
            if source.read_bytes()==dest.read_bytes(): raise ValueError(f'Stale audio: {name}')
            records.append({'file':name,'sha256':sha(source),'previous_sha256':sha(dest),'seconds':len(y)/sr,'peak':float(np.max(np.abs(y)))})
    receipt={'version':VERSION,'scores_changed':False,'inputs':inputs,'files':records,'human_listening':'pending'}
    write(output/'audio-verification.json',receipt)
    with zipfile.ZipFile(output/'previous-masters.zip','x',zipfile.ZIP_STORED) as z:
        for row in records:z.write(STUDIO/'assets/audio'/row['file'],row['file'])
    for row in records:shutil.copyfile(output/'audio'/row['file'],STUDIO/'assets/audio'/row['file'])
    archive=STUDIO/'downloads/neospc100-source-v4.zip';temp=output/'updated-source.zip'
    additions={
        'studio-v2/audio-verification.json':output/'audio-verification.json',
        'studio-v2/mix-report.json':output/'audio/mix-report.json',
        'studio-v2/bank-verification.json':output/'verification.json',
        'studio-v2/synthesize_soundbanks.py':SKILL/'scripts/synthesize_soundbanks.py',
        'studio-v2/render_mix_v4.py':SKILL/'scripts/render_mix_v4.py',
        'studio-v2/instrument-calibration.json':SKILL/'data/instrument-calibration.json',
    }
    with zipfile.ZipFile(archive) as old,zipfile.ZipFile(temp,'w',zipfile.ZIP_DEFLATED) as new:
        for item in old.infolist():
            if item.filename not in additions and item.filename!='STUDIO-V2-AUDIO.md':new.writestr(item,old.read(item.filename))
        for name,path in additions.items():new.write(path,name)
        new.writestr('STUDIO-V2-AUDIO.md','The R03 scores and MIDI remain unchanged. Studio v2 replaces all 200 audio files with freshly synthesized instruments. Current audio hashes and rendering sources are in studio-v2/. Earlier R03 verification records describe the original regeneration. Human listening is pending.\n')
    shutil.copyfile(temp,archive)
    print('Verified and published 200 fresh audio files; all 100 scores unchanged.')


def render(output):
    # Reuse the native renderer and its existing fresh-output contract.
    (output/'audio').mkdir(exist_ok=False)
    names=['game-music-composer/data/neospc100-benchmark-v4.1.json',
           'game-music-composer/scripts/render_mix_v4.py',
           'game-music-composer/data/instrument-calibration.json',
           'game-music-composer/resources/original-sample-bank/sample-bank.json']
    names += [p.relative_to(ROOT).as_posix() for p in sorted((SKILL/'resources/original-sample-bank').glob('*.wav'))]
    names.append('game-music-composer/scripts/synthesize_soundbanks.py')
    write(output/'render-inputs.json',{name:sha(ROOT/name) for name in names})
    subprocess.run([sys.executable,str(SKILL/'scripts/render_mix_v4.py'),str(SKILL/'data/neospc100-benchmark-v4.1.json'),
                    str(SKILL/'resources/original-sample-bank'),str(SKILL/'data/instrument-calibration.json'),
                    str(output/'audio'),'--workers','4'],check=True)


if __name__=='__main__':
    ap=argparse.ArgumentParser(description=__doc__);ap.add_argument('mode',choices=['build','publish','render','publish-audio']);ap.add_argument('output',type=Path)
    args=ap.parse_args();{'build':build,'publish':publish,'render':render,'publish-audio':publish_audio}[args.mode](args.output)
